-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    empty : IN STD_LOGIC_VECTOR (16 downto 0);
    sub59 : IN STD_LOGIC_VECTOR (31 downto 0);
    dst_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_1_ce1 : OUT STD_LOGIC;
    dst_1_we1 : OUT STD_LOGIC;
    dst_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_0_ce1 : OUT STD_LOGIC;
    dst_0_we1 : OUT STD_LOGIC;
    dst_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce0 : OUT STD_LOGIC;
    tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce1 : OUT STD_LOGIC;
    tmp_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln154_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_reg_395 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln155_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln155_reg_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_reg_405 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_reg_405_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln154_fu_223_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln154_reg_409 : STD_LOGIC_VECTOR (16 downto 0);
    signal cmp47_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_reg_414 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_reg_414_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp60_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp60_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp60_reg_419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_62_fu_254_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_62_reg_424 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln155_fu_258_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln155_reg_430 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln158_fu_282_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln158_reg_437 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln158_reg_437_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln3_reg_441 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln3_reg_441_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal v_reg_456 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_66_reg_466 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_2_fu_333_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_2_reg_471 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln158_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln160_fu_305_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln159_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln158_1_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_1_fu_58 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln155_fu_262_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_1_fu_62 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln154_1_fu_211_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten9_fu_66 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln154_fu_196_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln155_fu_182_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvars_iv_next2181_fu_205_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln154_fu_219_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_fu_248_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln158_fu_273_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln160_1_fu_296_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln160_1_fu_296_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln160_fu_300_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln159_fu_310_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_343_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal v_6_fu_314_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_8_fu_321_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_fu_327_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_343_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_343_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_mul_17s_17s_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component mti_process_ama_addmuladd_17s_1s_17s_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        din3 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component mti_process_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_17s_17s_17_1_1_U86 : component mti_process_mul_17s_17s_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        din0 => trunc_ln154_reg_409,
        din1 => empty,
        dout => empty_62_fu_254_p2);

    ama_addmuladd_17s_1s_17s_17ns_17_4_1_U87 : component mti_process_ama_addmuladd_17s_1s_17s_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 1,
        din2_WIDTH => 17,
        din3_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_343_p0,
        din1 => grp_fu_343_p1,
        din2 => empty,
        din3 => trunc_ln155_reg_430,
        ce => ap_const_logic_1,
        dout => grp_fu_343_p4);

    flow_control_loop_pipe_sequential_init_U : component mti_process_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    c_1_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_1_fu_58 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln154_reg_405 = ap_const_lv1_0))) then 
                    c_1_fu_58 <= add_ln155_fu_262_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten9_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                indvar_flatten9_fu_66 <= ap_const_lv64_0;
            elsif (((icmp_ln154_fu_191_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten9_fu_66 <= add_ln154_fu_196_p2;
            end if; 
        end if;
    end process;

    r_1_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                r_1_fu_62 <= ap_const_lv31_0;
            elsif (((icmp_ln154_fu_191_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                r_1_fu_62 <= select_ln154_1_fu_211_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                c_reg_395 <= c_1_fu_58;
                cmp47_reg_414 <= cmp47_fu_227_p2;
                cmp47_reg_414_pp0_iter1_reg <= cmp47_reg_414;
                cmp60_reg_419 <= cmp60_fu_233_p2;
                cmp60_reg_419_pp0_iter1_reg <= cmp60_reg_419;
                icmp_ln154_reg_405 <= icmp_ln154_fu_191_p2;
                icmp_ln154_reg_405_pp0_iter1_reg <= icmp_ln154_reg_405;
                icmp_ln155_reg_400 <= icmp_ln155_fu_186_p2;
                lshr_ln3_reg_441 <= add_ln158_fu_273_p2(16 downto 1);
                lshr_ln3_reg_441_pp0_iter2_reg <= lshr_ln3_reg_441;
                trunc_ln154_reg_409 <= trunc_ln154_fu_223_p1;
                trunc_ln158_reg_437 <= trunc_ln158_fu_282_p1;
                trunc_ln158_reg_437_pp0_iter2_reg <= trunc_ln158_reg_437;
                v_2_reg_471 <= v_2_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_62_reg_424 <= empty_62_fu_254_p2;
                trunc_ln155_reg_430 <= trunc_ln155_fu_258_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_66_reg_466 <= tmp_q0;
                v_reg_456 <= tmp_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage0, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln154_fu_196_p2 <= std_logic_vector(unsigned(indvar_flatten9_fu_66) + unsigned(ap_const_lv64_1));
    add_ln155_fu_262_p2 <= std_logic_vector(unsigned(select_ln154_fu_248_p3) + unsigned(ap_const_lv31_1));
    add_ln158_fu_273_p2 <= std_logic_vector(unsigned(trunc_ln155_reg_430) + unsigned(empty_62_reg_424));
    add_ln160_1_fu_296_p1 <= empty;
    add_ln160_1_fu_296_p2 <= std_logic_vector(unsigned(trunc_ln155_reg_430) + unsigned(add_ln160_1_fu_296_p1));
    add_ln160_fu_300_p2 <= std_logic_vector(unsigned(add_ln160_1_fu_296_p2) + unsigned(empty_62_reg_424));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln154_fu_191_p2)
    begin
        if (((icmp_ln154_fu_191_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln154_reg_405_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln154_reg_405_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cmp47_fu_227_p2 <= "0" when (select_ln154_1_fu_211_p3 = ap_const_lv31_0) else "1";
    cmp60_fu_233_p2 <= "1" when (signed(zext_ln154_fu_219_p1) < signed(sub59)) else "0";
    dst_0_address1 <= zext_ln158_1_fu_338_p1(16 - 1 downto 0);

    dst_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_0_ce1 <= ap_const_logic_1;
        else 
            dst_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    dst_0_d1 <= v_2_reg_471;

    dst_0_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln158_reg_437_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln158_reg_437_pp0_iter2_reg = ap_const_lv1_0))) then 
            dst_0_we1 <= ap_const_logic_1;
        else 
            dst_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    dst_1_address1 <= zext_ln158_1_fu_338_p1(16 - 1 downto 0);

    dst_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_1_ce1 <= ap_const_logic_1;
        else 
            dst_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    dst_1_d1 <= v_2_reg_471;

    dst_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln158_reg_437_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln158_reg_437_pp0_iter2_reg = ap_const_lv1_1))) then 
            dst_1_we1 <= ap_const_logic_1;
        else 
            dst_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_343_p0 <= select_ln154_1_fu_211_p3(17 - 1 downto 0);
    grp_fu_343_p1 <= ap_const_lv17_1FFFF(1 - 1 downto 0);
    icmp_ln154_fu_191_p2 <= "1" when (indvar_flatten9_fu_66 = bound) else "0";
    icmp_ln155_fu_186_p2 <= "1" when (signed(zext_ln155_fu_182_p1) < signed(width)) else "0";
    indvars_iv_next2181_fu_205_p2 <= std_logic_vector(unsigned(r_1_fu_62) + unsigned(ap_const_lv31_1));
    select_ln154_1_fu_211_p3 <= 
        r_1_fu_62 when (icmp_ln155_fu_186_p2(0) = '1') else 
        indvars_iv_next2181_fu_205_p2;
    select_ln154_fu_248_p3 <= 
        c_reg_395 when (icmp_ln155_reg_400(0) = '1') else 
        ap_const_lv31_0;
    tmp2_fu_327_p2 <= (v_8_fu_321_p3 or v_6_fu_314_p3);

    tmp_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln160_fu_305_p1, zext_ln159_fu_310_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tmp_address0 <= zext_ln159_fu_310_p1(17 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            tmp_address0 <= zext_ln160_fu_305_p1(17 - 1 downto 0);
        else 
            tmp_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    tmp_address1 <= zext_ln158_fu_277_p1(17 - 1 downto 0);

    tmp_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            tmp_ce0 <= ap_const_logic_1;
        else 
            tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            tmp_ce1 <= ap_const_logic_1;
        else 
            tmp_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln154_fu_223_p1 <= select_ln154_1_fu_211_p3(17 - 1 downto 0);
    trunc_ln155_fu_258_p1 <= select_ln154_fu_248_p3(17 - 1 downto 0);
    trunc_ln158_fu_282_p1 <= add_ln158_fu_273_p2(1 - 1 downto 0);
    v_2_fu_333_p2 <= (v_reg_456 or tmp2_fu_327_p2);
    v_6_fu_314_p3 <= 
        tmp_q0 when (cmp47_reg_414_pp0_iter1_reg(0) = '1') else 
        ap_const_lv8_0;
    v_8_fu_321_p3 <= 
        empty_66_reg_466 when (cmp60_reg_419_pp0_iter1_reg(0) = '1') else 
        ap_const_lv8_0;
    zext_ln154_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln154_1_fu_211_p3),32));
    zext_ln155_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_fu_58),32));
    zext_ln158_1_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_reg_441_pp0_iter2_reg),64));
    zext_ln158_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_fu_273_p2),64));
    zext_ln159_fu_310_p0 <= grp_fu_343_p4;
    zext_ln159_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln159_fu_310_p0),64));
    zext_ln160_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln160_fu_300_p2),64));
end behav;
