-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_box_blur_row is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src : IN STD_LOGIC_VECTOR (63 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    radius : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce1 : OUT STD_LOGIC;
    tmp_we1 : OUT STD_LOGIC;
    tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_box_blur_row is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sext_ln67_fu_133_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln67_reg_289 : STD_LOGIC_VECTOR (62 downto 0);
    signal k_fu_185_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal k_reg_294 : STD_LOGIC_VECTOR (9 downto 0);
    signal phi_mul_load_reg_300 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln71_fu_238_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln71_reg_310 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_idle : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_ready : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_sum_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_sum_out_ap_vld : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_idle : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_ready : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_ce1 : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_we1 : STD_LOGIC;
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln67_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal phi_mul_fu_66 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln67_1_fu_208_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal r_fu_70 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln67_fu_222_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln67_fu_133_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln67_fu_129_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln67_fu_137_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_147_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln67_fu_153_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln67_fu_153_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln67_fu_159_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln67_cast_fu_143_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_68_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_67_fu_167_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal umax_fu_177_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln67_1_fu_213_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_box_blur_row_Pipeline_VITIS_LOOP_71_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln71 : IN STD_LOGIC_VECTOR (9 downto 0);
        src : IN STD_LOGIC_VECTOR (63 downto 0);
        sext_ln71_2 : IN STD_LOGIC_VECTOR (62 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC );
    end component;


    component mti_process_box_blur_row_Pipeline_VITIS_LOOP_72_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln71_1 : IN STD_LOGIC_VECTOR (9 downto 0);
        sum_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        src : IN STD_LOGIC_VECTOR (63 downto 0);
        sext_ln71_2 : IN STD_LOGIC_VECTOR (62 downto 0);
        empty : IN STD_LOGIC_VECTOR (16 downto 0);
        zext_ln67_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln67 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln67 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce1 : OUT STD_LOGIC;
        tmp_we1 : OUT STD_LOGIC;
        tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102 : component mti_process_box_blur_row_Pipeline_VITIS_LOOP_71_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start,
        ap_done => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done,
        ap_idle => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_idle,
        ap_ready => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_ready,
        m_axi_gmem0_AWVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        sext_ln71 => k_reg_294,
        src => src,
        sext_ln71_2 => phi_mul_load_reg_300,
        sum_out => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_sum_out,
        sum_out_ap_vld => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_sum_out_ap_vld);

    grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112 : component mti_process_box_blur_row_Pipeline_VITIS_LOOP_72_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start,
        ap_done => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done,
        ap_idle => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_idle,
        ap_ready => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_ready,
        m_axi_gmem0_AWVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        sext_ln71_1 => k_reg_294,
        sum_reload => grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_sum_out,
        width => width,
        src => src,
        sext_ln71_2 => phi_mul_load_reg_300,
        empty => trunc_ln71_reg_310,
        zext_ln67_1 => radius,
        zext_ln67 => radius,
        sext_ln67 => width,
        tmp_address1 => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_address1,
        tmp_ce1 => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_ce1,
        tmp_we1 => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_we1,
        tmp_d1 => grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_ready = ap_const_logic_1)) then 
                    grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_ready = ap_const_logic_1)) then 
                    grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    phi_mul_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_mul_fu_66 <= ap_const_lv63_0;
            elsif (((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_mul_fu_66 <= add_ln67_1_fu_208_p2;
            end if; 
        end if;
    end process;

    r_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_fu_70 <= ap_const_lv31_0;
            elsif (((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                r_fu_70 <= add_ln67_fu_222_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                k_reg_294 <= k_fu_185_p2;
                sext_ln67_reg_289 <= sext_ln67_fu_133_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                phi_mul_load_reg_300 <= phi_mul_fu_66;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln71_reg_310 <= trunc_ln71_fu_238_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln67_fu_217_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln67_1_fu_208_p2 <= std_logic_vector(unsigned(phi_mul_fu_66) + unsigned(sext_ln67_reg_289));
    add_ln67_fu_222_p2 <= std_logic_vector(unsigned(r_fu_70) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done)
    begin
        if ((grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done)
    begin
        if ((grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln67_fu_217_p2)
    begin
        if ((((icmp_ln67_fu_217_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln67_fu_217_p2)
    begin
        if (((icmp_ln67_fu_217_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_67_fu_167_p1 <= select_ln67_fu_159_p3(10 - 1 downto 0);
    empty_68_fu_171_p2 <= "1" when (unsigned(sub_ln67_cast_fu_143_p1) > unsigned(select_ln67_fu_159_p3)) else "0";
    empty_fu_147_p0 <= width;
    empty_fu_147_p2 <= "1" when (signed(empty_fu_147_p0) > signed(ap_const_lv32_0)) else "0";
    grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_ap_start_reg;
    grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_ap_start_reg;
    icmp_ln67_fu_217_p2 <= "1" when (signed(zext_ln67_1_fu_213_p1) < signed(height)) else "0";
    k_fu_185_p2 <= (umax_fu_177_p3 xor ap_const_lv10_3FF);

    m_axi_gmem0_ARADDR_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARADDR, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARADDR, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARADDR <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARADDR <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARADDR;
        else 
            m_axi_gmem0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARBURST_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARBURST, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARBURST, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARBURST <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARBURST;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARBURST <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARBURST;
        else 
            m_axi_gmem0_ARBURST <= "XX";
        end if; 
    end process;


    m_axi_gmem0_ARCACHE_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARCACHE, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARCACHE, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARCACHE <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARCACHE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARCACHE <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARCACHE;
        else 
            m_axi_gmem0_ARCACHE <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARID_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARID, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARID, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARID <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARID <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARID;
        else 
            m_axi_gmem0_ARID <= "X";
        end if; 
    end process;


    m_axi_gmem0_ARLEN_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLEN, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLEN, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARLEN <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARLEN <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLEN;
        else 
            m_axi_gmem0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARLOCK_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLOCK, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLOCK, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARLOCK <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARLOCK;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARLOCK <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARLOCK;
        else 
            m_axi_gmem0_ARLOCK <= "XX";
        end if; 
    end process;


    m_axi_gmem0_ARPROT_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARPROT, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARPROT, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARPROT <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARPROT;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARPROT <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARPROT;
        else 
            m_axi_gmem0_ARPROT <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_ARQOS_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARQOS, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARQOS, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARQOS <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARQOS;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARQOS <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARQOS;
        else 
            m_axi_gmem0_ARQOS <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARREGION_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARREGION, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARREGION, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARREGION <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARREGION;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARREGION <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARREGION;
        else 
            m_axi_gmem0_ARREGION <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARSIZE_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARSIZE, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARSIZE, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARSIZE <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARSIZE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARSIZE <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARSIZE;
        else 
            m_axi_gmem0_ARSIZE <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_ARUSER_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARUSER, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARUSER, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARUSER <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARUSER;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARUSER <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARUSER;
        else 
            m_axi_gmem0_ARUSER <= "X";
        end if; 
    end process;


    m_axi_gmem0_ARVALID_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARVALID, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARVALID, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARVALID <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_ARVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_ARVALID <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_ARVALID;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_RREADY, grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_RREADY, icmp_ln67_fu_217_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_RREADY <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_m_axi_gmem0_RREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln67_fu_217_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            m_axi_gmem0_RREADY <= grp_box_blur_row_Pipeline_VITIS_LOOP_71_2_fu_102_m_axi_gmem0_RREADY;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    select_ln67_fu_159_p3 <= 
        xor_ln67_fu_153_p2 when (empty_fu_147_p2(0) = '1') else 
        ap_const_lv32_FFFFFFFF;
    sext_ln67_fu_133_p0 <= width;
        sext_ln67_fu_133_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln67_fu_133_p0),63));

        sub_ln67_cast_fu_143_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln67_fu_137_p2),32));

    sub_ln67_fu_137_p2 <= std_logic_vector(signed(ap_const_lv10_3FE) - signed(zext_ln67_fu_129_p1));
    tmp_address1 <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_address1;
    tmp_ce1 <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_ce1;
    tmp_d1 <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_d1;
    tmp_we1 <= grp_box_blur_row_Pipeline_VITIS_LOOP_72_3_fu_112_tmp_we1;
    trunc_ln71_fu_238_p1 <= phi_mul_load_reg_300(17 - 1 downto 0);
    umax_fu_177_p3 <= 
        sub_ln67_fu_137_p2 when (empty_68_fu_171_p2(0) = '1') else 
        empty_67_fu_167_p1;
    xor_ln67_fu_153_p0 <= width;
    xor_ln67_fu_153_p2 <= (xor_ln67_fu_153_p0 xor ap_const_lv32_FFFFFFFF);
    zext_ln67_1_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_70),32));
    zext_ln67_fu_129_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(radius),10));
end behav;
