-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_dilate_3x3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_0_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_0_ce0 : OUT STD_LOGIC;
    src_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_0_ce1 : OUT STD_LOGIC;
    src_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_1_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_1_ce0 : OUT STD_LOGIC;
    src_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_1_ce1 : OUT STD_LOGIC;
    src_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    dst_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_0_ce1 : OUT STD_LOGIC;
    dst_0_we1 : OUT STD_LOGIC;
    dst_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_1_ce1 : OUT STD_LOGIC;
    dst_1_we1 : OUT STD_LOGIC;
    dst_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce0 : OUT STD_LOGIC;
    tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce1 : OUT STD_LOGIC;
    tmp_we1 : OUT STD_LOGIC;
    tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tmp_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_dilate_3x3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln145_fu_74_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln145_reg_112 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_70_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_128 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub12_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub12_reg_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sub59_fu_94_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub59_reg_139 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_idle : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_ready : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce0 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce0 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_we1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_idle : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_ready : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_we1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_we1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce0 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce1 : STD_LOGIC;
    signal grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_70_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_70_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal grp_fu_70_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_70_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        empty : IN STD_LOGIC_VECTOR (16 downto 0);
        src_0_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        src_0_ce0 : OUT STD_LOGIC;
        src_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        src_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        src_0_ce1 : OUT STD_LOGIC;
        src_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        src_1_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        src_1_ce0 : OUT STD_LOGIC;
        src_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        src_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        src_1_ce1 : OUT STD_LOGIC;
        src_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sub12 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce1 : OUT STD_LOGIC;
        tmp_we1 : OUT STD_LOGIC;
        tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mti_process_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        empty : IN STD_LOGIC_VECTOR (16 downto 0);
        sub59 : IN STD_LOGIC_VECTOR (31 downto 0);
        dst_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dst_1_ce1 : OUT STD_LOGIC;
        dst_1_we1 : OUT STD_LOGIC;
        dst_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dst_0_ce1 : OUT STD_LOGIC;
        dst_0_we1 : OUT STD_LOGIC;
        dst_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce1 : OUT STD_LOGIC;
        tmp_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mti_process_mul_32ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42 : component mti_process_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start,
        ap_done => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done,
        ap_idle => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_idle,
        ap_ready => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_ready,
        width => width,
        bound => bound_reg_128,
        empty => trunc_ln145_reg_112,
        src_0_address0 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address0,
        src_0_ce0 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce0,
        src_0_q0 => src_0_q0,
        src_0_address1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address1,
        src_0_ce1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce1,
        src_0_q1 => src_0_q1,
        src_1_address0 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address0,
        src_1_ce0 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce0,
        src_1_q0 => src_1_q0,
        src_1_address1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address1,
        src_1_ce1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce1,
        src_1_q1 => src_1_q1,
        sub12 => sub12_reg_134,
        tmp_address1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_address1,
        tmp_ce1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_ce1,
        tmp_we1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_we1,
        tmp_d1 => grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_d1);

    grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56 : component mti_process_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start,
        ap_done => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done,
        ap_idle => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_idle,
        ap_ready => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_ready,
        width => width,
        bound => bound_reg_128,
        empty => trunc_ln145_reg_112,
        sub59 => sub59_reg_139,
        dst_1_address1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_address1,
        dst_1_ce1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_ce1,
        dst_1_we1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_we1,
        dst_1_d1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_d1,
        dst_0_address1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_address1,
        dst_0_ce1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_ce1,
        dst_0_we1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_we1,
        dst_0_d1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_d1,
        tmp_address0 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address0,
        tmp_ce0 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce0,
        tmp_q0 => tmp_q0,
        tmp_address1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address1,
        tmp_ce1 => grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce1,
        tmp_q1 => tmp_q1);

    mul_32ns_32ns_64_2_1_U97 : component mti_process_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_70_p0,
        din1 => grp_fu_70_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_70_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_ready = ap_const_logic_1)) then 
                    grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_128 <= grp_fu_70_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                sub12_reg_134 <= sub12_fu_88_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sub59_reg_139 <= sub59_fu_94_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln145_reg_112 <= trunc_ln145_fu_74_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done, grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done)
    begin
        if ((grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done)
    begin
        if ((grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done, ap_CS_fsm_state6)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dst_0_address1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_address1;
    dst_0_ce1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_ce1;
    dst_0_d1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_d1;
    dst_0_we1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_0_we1;
    dst_1_address1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_address1;
    dst_1_ce1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_ce1;
    dst_1_d1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_d1;
    dst_1_we1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_dst_1_we1;
    grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_ap_start_reg;
    grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_ap_start_reg;
    grp_fu_70_p0 <= grp_fu_70_p00(32 - 1 downto 0);
    grp_fu_70_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),64));
    grp_fu_70_p1 <= grp_fu_70_p10(32 - 1 downto 0);
    grp_fu_70_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),64));
    src_0_address0 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address0;
    src_0_address1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_address1;
    src_0_ce0 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce0;
    src_0_ce1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_0_ce1;
    src_1_address0 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address0;
    src_1_address1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_address1;
    src_1_ce0 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce0;
    src_1_ce1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_src_1_ce1;
    sub12_fu_88_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv32_FFFFFFFF));
    sub59_fu_94_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv32_FFFFFFFF));
    tmp_address0 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address0;

    tmp_address1_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_address1, grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address1, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            tmp_address1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            tmp_address1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_address1;
        else 
            tmp_address1 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_ce0_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            tmp_ce0 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce0;
        else 
            tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_ce1_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_ce1, grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce1, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            tmp_ce1 <= grp_dilate_3x3_Pipeline_DIL_COL_VITIS_LOOP_155_2_fu_56_tmp_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            tmp_ce1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_ce1;
        else 
            tmp_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_d1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_d1;

    tmp_we1_assign_proc : process(grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_we1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            tmp_we1 <= grp_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1_fu_42_tmp_we1;
        else 
            tmp_we1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln145_fu_74_p1 <= width(17 - 1 downto 0);
end behav;
