-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_box_blur_col is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    radius : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce0 : OUT STD_LOGIC;
    tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    blurred_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    blurred_ce1 : OUT STD_LOGIC;
    blurred_we1 : OUT STD_LOGIC;
    blurred_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_box_blur_col is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln91_fu_102_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln91_reg_227 : STD_LOGIC_VECTOR (16 downto 0);
    signal k_fu_154_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal k_reg_233 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln91_1_fu_183_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln91_1_reg_242 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_idle : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_ready : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_sum_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_sum_out_ap_vld : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_ce0 : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_idle : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_ready : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_ce1 : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_we1 : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_ce0 : STD_LOGIC;
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln91_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal c_fu_46 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln91_fu_177_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln91_fu_98_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln91_fu_106_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln91_fu_122_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln91_fu_128_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln91_cast_fu_112_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_78_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_77_fu_136_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal umax_fu_146_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln91_1_fu_168_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_box_blur_col_Pipeline_VITIS_LOOP_93_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln93 : IN STD_LOGIC_VECTOR (9 downto 0);
        empty_46 : IN STD_LOGIC_VECTOR (16 downto 0);
        empty : IN STD_LOGIC_VECTOR (16 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC;
        tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mti_process_box_blur_col_Pipeline_VITIS_LOOP_94_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln93_1 : IN STD_LOGIC_VECTOR (9 downto 0);
        sum_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_45 : IN STD_LOGIC_VECTOR (16 downto 0);
        empty : IN STD_LOGIC_VECTOR (16 downto 0);
        zext_ln91_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln91 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln91 : IN STD_LOGIC_VECTOR (31 downto 0);
        blurred_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        blurred_ce1 : OUT STD_LOGIC;
        blurred_we1 : OUT STD_LOGIC;
        blurred_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        tmp_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72 : component mti_process_box_blur_col_Pipeline_VITIS_LOOP_93_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start,
        ap_done => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done,
        ap_idle => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_idle,
        ap_ready => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_ready,
        sext_ln93 => k_reg_233,
        empty_46 => trunc_ln91_reg_227,
        empty => trunc_ln91_1_reg_242,
        sum_out => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_sum_out,
        sum_out_ap_vld => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_sum_out_ap_vld,
        tmp_address0 => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_address0,
        tmp_ce0 => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_ce0,
        tmp_q0 => tmp_q0);

    grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82 : component mti_process_box_blur_col_Pipeline_VITIS_LOOP_94_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start,
        ap_done => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done,
        ap_idle => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_idle,
        ap_ready => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_ready,
        sext_ln93_1 => k_reg_233,
        sum_reload => grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_sum_out,
        height => height,
        empty_45 => trunc_ln91_reg_227,
        empty => trunc_ln91_1_reg_242,
        zext_ln91_1 => radius,
        zext_ln91 => radius,
        sext_ln91 => height,
        blurred_address1 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_address1,
        blurred_ce1 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_ce1,
        blurred_we1 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_we1,
        blurred_d1 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_d1,
        tmp_address0 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_address0,
        tmp_ce0 => grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_ce0,
        tmp_q0 => tmp_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln91_fu_172_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_ready = ap_const_logic_1)) then 
                    grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_fu_46 <= ap_const_lv31_0;
            elsif (((icmp_ln91_fu_172_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_fu_46 <= add_ln91_fu_177_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                k_reg_233 <= k_fu_154_p2;
                trunc_ln91_reg_227 <= trunc_ln91_fu_102_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln91_1_reg_242 <= trunc_ln91_1_fu_183_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done, grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done, icmp_ln91_fu_172_p2, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln91_fu_172_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln91_fu_177_p2 <= std_logic_vector(unsigned(c_fu_46) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done)
    begin
        if ((grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done)
    begin
        if ((grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln91_fu_172_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln91_fu_172_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln91_fu_172_p2)
    begin
        if (((icmp_ln91_fu_172_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    blurred_address1 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_address1;
    blurred_ce1 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_ce1;
    blurred_d1 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_d1;
    blurred_we1 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_blurred_we1;
    empty_77_fu_136_p1 <= select_ln91_fu_128_p3(10 - 1 downto 0);
    empty_78_fu_140_p2 <= "1" when (unsigned(sub_ln91_cast_fu_112_p1) > unsigned(select_ln91_fu_128_p3)) else "0";
    empty_fu_116_p2 <= "1" when (signed(height) > signed(ap_const_lv32_0)) else "0";
    grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start <= grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_ap_start_reg;
    grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_ap_start_reg;
    icmp_ln91_fu_172_p2 <= "1" when (signed(zext_ln91_1_fu_168_p1) < signed(width)) else "0";
    k_fu_154_p2 <= (umax_fu_146_p3 xor ap_const_lv10_3FF);
    select_ln91_fu_128_p3 <= 
        xor_ln91_fu_122_p2 when (empty_fu_116_p2(0) = '1') else 
        ap_const_lv32_FFFFFFFF;
        sub_ln91_cast_fu_112_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln91_fu_106_p2),32));

    sub_ln91_fu_106_p2 <= std_logic_vector(signed(ap_const_lv10_3FE) - signed(zext_ln91_fu_98_p1));

    tmp_address0_assign_proc : process(grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_address0, grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_address0 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_address0 <= grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_address0;
        else 
            tmp_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_ce0_assign_proc : process(grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_ce0, grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_ce0 <= grp_box_blur_col_Pipeline_VITIS_LOOP_94_3_fu_82_tmp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_ce0 <= grp_box_blur_col_Pipeline_VITIS_LOOP_93_2_fu_72_tmp_ce0;
        else 
            tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln91_1_fu_183_p1 <= c_fu_46(17 - 1 downto 0);
    trunc_ln91_fu_102_p1 <= width(17 - 1 downto 0);
    umax_fu_146_p3 <= 
        sub_ln91_fu_106_p2 when (empty_78_fu_140_p2(0) = '1') else 
        empty_77_fu_136_p1;
    xor_ln91_fu_122_p2 <= (height xor ap_const_lv32_FFFFFFFF);
    zext_ln91_1_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_46),32));
    zext_ln91_fu_98_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(radius),10));
end behav;
