-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    empty : IN STD_LOGIC_VECTOR (16 downto 0);
    src_0_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_0_ce0 : OUT STD_LOGIC;
    src_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_0_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_0_ce1 : OUT STD_LOGIC;
    src_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_1_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_1_ce0 : OUT STD_LOGIC;
    src_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    src_1_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    src_1_ce1 : OUT STD_LOGIC;
    src_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    sub12 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce1 : OUT STD_LOGIC;
    tmp_we1 : OUT STD_LOGIC;
    tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_dilate_3x3_Pipeline_DIL_ROW_VITIS_LOOP_146_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln145_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_2_reg_445 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln146_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln146_reg_450 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln145_reg_455 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln146_fu_261_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln146_reg_464 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln150_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_reg_469_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_reg_474 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_reg_474_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_396_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln149_reg_479 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln149_reg_479_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln149_fu_287_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln149_reg_486 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_0_load_reg_503 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_1_load_reg_508 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_1_fu_386_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_1_reg_533 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln149_1_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln150_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln151_fu_341_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln149_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_60 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln146_fu_276_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_64 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln145_1_fu_229_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_68 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln145_fu_214_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln146_fu_200_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln145_1_fu_223_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln145_fu_251_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln145_fu_257_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln149_fu_287_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln_fu_290_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln_fu_290_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln150_fu_310_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln150_fu_310_p2 : signal is "no";
    signal lshr_ln1_fu_315_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln149_1_fu_305_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln149_1_fu_305_p2 : signal is "no";
    signal lshr_ln2_fu_331_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln150_fu_352_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln151_fu_366_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln150_1_fu_359_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln151_1_fu_373_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln151_fu_380_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal v_fu_347_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_396_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_mac_muladd_17s_17s_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component mti_process_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_17s_17s_17ns_17_4_1_U78 : component mti_process_mac_muladd_17s_17s_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 17,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_396_p0,
        din1 => empty,
        din2 => trunc_ln146_reg_464,
        ce => ap_const_logic_1,
        dout => grp_fu_396_p3);

    flow_control_loop_pipe_sequential_init_U : component mti_process_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    c_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_60 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln145_reg_455 = ap_const_lv1_0))) then 
                    c_fu_60 <= add_ln146_fu_276_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                indvar_flatten_fu_68 <= ap_const_lv64_0;
            elsif (((icmp_ln145_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten_fu_68 <= add_ln145_fu_214_p2;
            end if; 
        end if;
    end process;

    r_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                r_fu_64 <= ap_const_lv31_0;
            elsif (((icmp_ln145_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                r_fu_64 <= select_ln145_1_fu_229_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln149_reg_479 <= grp_fu_396_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln149_reg_479_pp0_iter3_reg <= add_ln149_reg_479;
                icmp_ln150_reg_469 <= icmp_ln150_fu_265_p2;
                icmp_ln150_reg_469_pp0_iter2_reg <= icmp_ln150_reg_469;
                icmp_ln151_reg_474 <= icmp_ln151_fu_271_p2;
                icmp_ln151_reg_474_pp0_iter2_reg <= icmp_ln151_reg_474;
                trunc_ln146_reg_464 <= trunc_ln146_fu_261_p1;
                trunc_ln149_reg_486 <= trunc_ln149_fu_287_p1;
                v_1_reg_533 <= v_1_fu_386_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                c_2_reg_445 <= c_fu_60;
                icmp_ln145_reg_455 <= icmp_ln145_fu_209_p2;
                icmp_ln146_reg_450 <= icmp_ln146_fu_204_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                src_0_load_reg_503 <= src_0_q0;
                src_1_load_reg_508 <= src_1_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln145_1_fu_223_p2 <= std_logic_vector(unsigned(r_fu_64) + unsigned(ap_const_lv31_1));
    add_ln145_fu_214_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_68) + unsigned(ap_const_lv64_1));
    add_ln146_fu_276_p2 <= std_logic_vector(unsigned(select_ln145_fu_251_p3) + unsigned(ap_const_lv31_1));
    add_ln149_1_fu_305_p2 <= std_logic_vector(signed(add_ln149_reg_479) + signed(ap_const_lv17_1));
    add_ln150_fu_310_p2 <= std_logic_vector(signed(add_ln149_reg_479) + signed(ap_const_lv17_1FFFF));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln145_fu_209_p2)
    begin
        if (((icmp_ln145_fu_209_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_396_p0 <= select_ln145_1_fu_229_p3(17 - 1 downto 0);
    icmp_ln145_fu_209_p2 <= "1" when (indvar_flatten_fu_68 = bound) else "0";
    icmp_ln146_fu_204_p2 <= "1" when (signed(zext_ln146_fu_200_p1) < signed(width)) else "0";
    icmp_ln150_fu_265_p2 <= "0" when (select_ln145_fu_251_p3 = ap_const_lv31_0) else "1";
    icmp_ln151_fu_271_p2 <= "1" when (signed(zext_ln145_fu_257_p1) < signed(sub12)) else "0";
    lshr_ln1_fu_315_p4 <= add_ln150_fu_310_p2(16 downto 1);
    lshr_ln2_fu_331_p4 <= add_ln149_1_fu_305_p2(16 downto 1);
    lshr_ln_fu_290_p1 <= grp_fu_396_p3;
    lshr_ln_fu_290_p4 <= lshr_ln_fu_290_p1(16 downto 1);
    or_ln151_fu_380_p2 <= (select_ln151_1_fu_373_p3 or select_ln150_1_fu_359_p3);
    select_ln145_1_fu_229_p3 <= 
        r_fu_64 when (icmp_ln146_fu_204_p2(0) = '1') else 
        add_ln145_1_fu_223_p2;
    select_ln145_fu_251_p3 <= 
        c_2_reg_445 when (icmp_ln146_reg_450(0) = '1') else 
        ap_const_lv31_0;
    select_ln150_1_fu_359_p3 <= 
        select_ln150_fu_352_p3 when (icmp_ln150_reg_469_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln150_fu_352_p3 <= 
        src_0_q1 when (trunc_ln149_reg_486(0) = '1') else 
        src_1_q1;
    select_ln151_1_fu_373_p3 <= 
        select_ln151_fu_366_p3 when (icmp_ln151_reg_474_pp0_iter2_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln151_fu_366_p3 <= 
        src_0_q0 when (trunc_ln149_reg_486(0) = '1') else 
        src_1_q0;

    src_0_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, zext_ln149_1_fu_299_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln151_fu_341_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                src_0_address0 <= zext_ln151_fu_341_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                src_0_address0 <= zext_ln149_1_fu_299_p1(16 - 1 downto 0);
            else 
                src_0_address0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            src_0_address0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    src_0_address1 <= zext_ln150_fu_325_p1(16 - 1 downto 0);

    src_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            src_0_ce0 <= ap_const_logic_1;
        else 
            src_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    src_0_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            src_0_ce1 <= ap_const_logic_1;
        else 
            src_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    src_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, zext_ln149_1_fu_299_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln151_fu_341_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                src_1_address0 <= zext_ln151_fu_341_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                src_1_address0 <= zext_ln149_1_fu_299_p1(16 - 1 downto 0);
            else 
                src_1_address0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            src_1_address0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    src_1_address1 <= zext_ln150_fu_325_p1(16 - 1 downto 0);

    src_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            src_1_ce0 <= ap_const_logic_1;
        else 
            src_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    src_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            src_1_ce1 <= ap_const_logic_1;
        else 
            src_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_address1 <= zext_ln149_fu_392_p1(17 - 1 downto 0);

    tmp_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            tmp_ce1 <= ap_const_logic_1;
        else 
            tmp_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_d1 <= v_1_reg_533;

    tmp_we1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            tmp_we1 <= ap_const_logic_1;
        else 
            tmp_we1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln146_fu_261_p1 <= select_ln145_fu_251_p3(17 - 1 downto 0);
    trunc_ln149_fu_287_p0 <= grp_fu_396_p3;
    trunc_ln149_fu_287_p1 <= trunc_ln149_fu_287_p0(1 - 1 downto 0);
    v_1_fu_386_p2 <= (v_fu_347_p3 or or_ln151_fu_380_p2);
    v_fu_347_p3 <= 
        src_1_load_reg_508 when (trunc_ln149_reg_486(0) = '1') else 
        src_0_load_reg_503;
    zext_ln145_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_fu_251_p3),32));
    zext_ln146_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_60),32));
    zext_ln149_1_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_290_p4),64));
    zext_ln149_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln149_reg_479_pp0_iter3_reg),64));
    zext_ln150_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_315_p4),64));
    zext_ln151_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_331_p4),64));
end behav;
