-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mti_process_box_blur_row_Pipeline_VITIS_LOOP_72_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln71_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    sum_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    src : IN STD_LOGIC_VECTOR (63 downto 0);
    sext_ln71_2 : IN STD_LOGIC_VECTOR (62 downto 0);
    empty : IN STD_LOGIC_VECTOR (16 downto 0);
    zext_ln67_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln67 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln67 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    tmp_ce1 : OUT STD_LOGIC;
    tmp_we1 : OUT STD_LOGIC;
    tmp_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mti_process_box_blur_row_Pipeline_VITIS_LOOP_72_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln72_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op99_readreq_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal icmp_ln72_reg_476_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_506_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op122_read_state12 : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter5 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln77_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_496_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op97_readreq_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_predicate_op112_read_state11 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln71_2_cast_fu_247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln71_2_cast_reg_470 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln72_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_reg_476_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_fu_293_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter1_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter5_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter6_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter7_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter8_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter9_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter10_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter11_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter12_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter13_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter14_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter15_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter16_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter17_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter18_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter19_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter20_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter21_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter22_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln75_reg_480_pp0_iter23_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_fu_309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_reg_485 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln76_fu_319_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln76_reg_490 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln77_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_496_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_496_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_496_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_496_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_addr_reg_500 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_29_reg_506_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_506_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_506_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_506_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_addr_1_reg_510 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem0_addr_read_reg_516 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_4_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cnt_6_fu_402_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem0_addr_1_read_reg_543 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_387_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sdiv_ln75_reg_548 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_condition_exit_pp0_iter5_stage1 : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_sum_2_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_cnt_2_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_sum_3_phi_fu_218_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_5_fu_411_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_sum_3_reg_215 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_cnt_3_phi_fu_228_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal cnt_7_fu_418_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_cnt_3_reg_225 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln75_fu_439_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln77_1_fu_347_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln78_1_fu_370_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_90 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln72_fu_283_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sum_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal cnt_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sext_ln71_1_cast_fu_251_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln72_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln72_fu_289_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln67_1_cast_fu_243_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_1_fu_299_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln76_fu_305_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln67_cast_fu_239_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln76_2_fu_315_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln67_cast_fu_235_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln76_1_fu_336_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln77_fu_342_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln77_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln78_fu_365_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln77_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln78_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_387_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to23 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_486 : BOOLEAN;
    signal ap_condition_796 : BOOLEAN;
    signal ap_condition_799 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component mti_process_sdiv_32ns_32ns_8_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component mti_process_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sdiv_32ns_32ns_8_36_1_U6 : component mti_process_sdiv_32ns_32ns_8_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_fu_94,
        din1 => cnt_fu_98,
        ce => grp_fu_387_ce,
        dout => grp_fu_387_p2);

    flow_control_loop_pipe_sequential_init_U : component mti_process_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter22_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage1)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter6_cnt_2_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_486)) then
                if (((icmp_ln77_reg_496_pp0_iter5_reg = ap_const_lv1_0) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter6_cnt_2_reg_206 <= cnt_fu_98;
                elsif (((icmp_ln77_reg_496_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter6_cnt_2_reg_206 <= cnt_6_fu_402_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter6_cnt_2_reg_206 <= ap_phi_reg_pp0_iter5_cnt_2_reg_206;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter6_sum_2_reg_197_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_486)) then
                if (((icmp_ln77_reg_496_pp0_iter5_reg = ap_const_lv1_0) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter6_sum_2_reg_197 <= sum_fu_94;
                elsif (((icmp_ln77_reg_496_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter6_sum_2_reg_197 <= sum_4_fu_396_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter6_sum_2_reg_197 <= ap_phi_reg_pp0_iter5_sum_2_reg_197;
                end if;
            end if; 
        end if;
    end process;

    c_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln72_fu_277_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_90 <= add_ln72_fu_283_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_90 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;

    cnt_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    cnt_fu_98 <= sext_ln71_1_cast_fu_251_p1;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    cnt_fu_98 <= ap_phi_mux_cnt_3_phi_fu_228_p4;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    sum_fu_94 <= sum_reload;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    sum_fu_94 <= ap_phi_mux_sum_3_phi_fu_218_p4;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln75_reg_480 <= add_ln75_fu_293_p2;
                add_ln75_reg_480_pp0_iter10_reg <= add_ln75_reg_480_pp0_iter9_reg;
                add_ln75_reg_480_pp0_iter11_reg <= add_ln75_reg_480_pp0_iter10_reg;
                add_ln75_reg_480_pp0_iter12_reg <= add_ln75_reg_480_pp0_iter11_reg;
                add_ln75_reg_480_pp0_iter13_reg <= add_ln75_reg_480_pp0_iter12_reg;
                add_ln75_reg_480_pp0_iter14_reg <= add_ln75_reg_480_pp0_iter13_reg;
                add_ln75_reg_480_pp0_iter15_reg <= add_ln75_reg_480_pp0_iter14_reg;
                add_ln75_reg_480_pp0_iter16_reg <= add_ln75_reg_480_pp0_iter15_reg;
                add_ln75_reg_480_pp0_iter17_reg <= add_ln75_reg_480_pp0_iter16_reg;
                add_ln75_reg_480_pp0_iter18_reg <= add_ln75_reg_480_pp0_iter17_reg;
                add_ln75_reg_480_pp0_iter19_reg <= add_ln75_reg_480_pp0_iter18_reg;
                add_ln75_reg_480_pp0_iter1_reg <= add_ln75_reg_480;
                add_ln75_reg_480_pp0_iter20_reg <= add_ln75_reg_480_pp0_iter19_reg;
                add_ln75_reg_480_pp0_iter21_reg <= add_ln75_reg_480_pp0_iter20_reg;
                add_ln75_reg_480_pp0_iter22_reg <= add_ln75_reg_480_pp0_iter21_reg;
                add_ln75_reg_480_pp0_iter23_reg <= add_ln75_reg_480_pp0_iter22_reg;
                add_ln75_reg_480_pp0_iter2_reg <= add_ln75_reg_480_pp0_iter1_reg;
                add_ln75_reg_480_pp0_iter3_reg <= add_ln75_reg_480_pp0_iter2_reg;
                add_ln75_reg_480_pp0_iter4_reg <= add_ln75_reg_480_pp0_iter3_reg;
                add_ln75_reg_480_pp0_iter5_reg <= add_ln75_reg_480_pp0_iter4_reg;
                add_ln75_reg_480_pp0_iter6_reg <= add_ln75_reg_480_pp0_iter5_reg;
                add_ln75_reg_480_pp0_iter7_reg <= add_ln75_reg_480_pp0_iter6_reg;
                add_ln75_reg_480_pp0_iter8_reg <= add_ln75_reg_480_pp0_iter7_reg;
                add_ln75_reg_480_pp0_iter9_reg <= add_ln75_reg_480_pp0_iter8_reg;
                add_ln76_reg_485 <= add_ln76_fu_309_p2;
                gmem0_addr_read_reg_516 <= m_axi_gmem0_RDATA;
                icmp_ln72_reg_476 <= icmp_ln72_fu_277_p2;
                icmp_ln72_reg_476_pp0_iter10_reg <= icmp_ln72_reg_476_pp0_iter9_reg;
                icmp_ln72_reg_476_pp0_iter11_reg <= icmp_ln72_reg_476_pp0_iter10_reg;
                icmp_ln72_reg_476_pp0_iter12_reg <= icmp_ln72_reg_476_pp0_iter11_reg;
                icmp_ln72_reg_476_pp0_iter13_reg <= icmp_ln72_reg_476_pp0_iter12_reg;
                icmp_ln72_reg_476_pp0_iter14_reg <= icmp_ln72_reg_476_pp0_iter13_reg;
                icmp_ln72_reg_476_pp0_iter15_reg <= icmp_ln72_reg_476_pp0_iter14_reg;
                icmp_ln72_reg_476_pp0_iter16_reg <= icmp_ln72_reg_476_pp0_iter15_reg;
                icmp_ln72_reg_476_pp0_iter17_reg <= icmp_ln72_reg_476_pp0_iter16_reg;
                icmp_ln72_reg_476_pp0_iter18_reg <= icmp_ln72_reg_476_pp0_iter17_reg;
                icmp_ln72_reg_476_pp0_iter19_reg <= icmp_ln72_reg_476_pp0_iter18_reg;
                icmp_ln72_reg_476_pp0_iter1_reg <= icmp_ln72_reg_476;
                icmp_ln72_reg_476_pp0_iter20_reg <= icmp_ln72_reg_476_pp0_iter19_reg;
                icmp_ln72_reg_476_pp0_iter21_reg <= icmp_ln72_reg_476_pp0_iter20_reg;
                icmp_ln72_reg_476_pp0_iter22_reg <= icmp_ln72_reg_476_pp0_iter21_reg;
                icmp_ln72_reg_476_pp0_iter23_reg <= icmp_ln72_reg_476_pp0_iter22_reg;
                icmp_ln72_reg_476_pp0_iter2_reg <= icmp_ln72_reg_476_pp0_iter1_reg;
                icmp_ln72_reg_476_pp0_iter3_reg <= icmp_ln72_reg_476_pp0_iter2_reg;
                icmp_ln72_reg_476_pp0_iter4_reg <= icmp_ln72_reg_476_pp0_iter3_reg;
                icmp_ln72_reg_476_pp0_iter5_reg <= icmp_ln72_reg_476_pp0_iter4_reg;
                icmp_ln72_reg_476_pp0_iter6_reg <= icmp_ln72_reg_476_pp0_iter5_reg;
                icmp_ln72_reg_476_pp0_iter7_reg <= icmp_ln72_reg_476_pp0_iter6_reg;
                icmp_ln72_reg_476_pp0_iter8_reg <= icmp_ln72_reg_476_pp0_iter7_reg;
                icmp_ln72_reg_476_pp0_iter9_reg <= icmp_ln72_reg_476_pp0_iter8_reg;
                icmp_ln77_reg_496 <= icmp_ln77_fu_325_p2;
                icmp_ln77_reg_496_pp0_iter1_reg <= icmp_ln77_reg_496;
                icmp_ln77_reg_496_pp0_iter2_reg <= icmp_ln77_reg_496_pp0_iter1_reg;
                icmp_ln77_reg_496_pp0_iter3_reg <= icmp_ln77_reg_496_pp0_iter2_reg;
                icmp_ln77_reg_496_pp0_iter4_reg <= icmp_ln77_reg_496_pp0_iter3_reg;
                icmp_ln77_reg_496_pp0_iter5_reg <= icmp_ln77_reg_496_pp0_iter4_reg;
                sdiv_ln75_reg_548 <= grp_fu_387_p2;
                sext_ln71_2_cast_reg_470 <= sext_ln71_2_cast_fu_247_p1;
                sub_ln76_reg_490 <= sub_ln76_fu_319_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem0_addr_1_read_reg_543 <= m_axi_gmem0_RDATA;
                gmem0_addr_1_reg_510 <= add_ln78_1_fu_370_p2;
                gmem0_addr_reg_500 <= add_ln77_1_fu_347_p2;
                tmp_29_reg_506 <= sub_ln76_reg_490(31 downto 31);
                tmp_29_reg_506_pp0_iter1_reg <= tmp_29_reg_506;
                tmp_29_reg_506_pp0_iter2_reg <= tmp_29_reg_506_pp0_iter1_reg;
                tmp_29_reg_506_pp0_iter3_reg <= tmp_29_reg_506_pp0_iter2_reg;
                tmp_29_reg_506_pp0_iter4_reg <= tmp_29_reg_506_pp0_iter3_reg;
                tmp_29_reg_506_pp0_iter5_reg <= tmp_29_reg_506_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_phi_reg_pp0_iter1_cnt_2_reg_206 <= ap_phi_reg_pp0_iter0_cnt_2_reg_206;
                ap_phi_reg_pp0_iter1_sum_2_reg_197 <= ap_phi_reg_pp0_iter0_sum_2_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_phi_reg_pp0_iter2_cnt_2_reg_206 <= ap_phi_reg_pp0_iter1_cnt_2_reg_206;
                ap_phi_reg_pp0_iter2_sum_2_reg_197 <= ap_phi_reg_pp0_iter1_sum_2_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_phi_reg_pp0_iter3_cnt_2_reg_206 <= ap_phi_reg_pp0_iter2_cnt_2_reg_206;
                ap_phi_reg_pp0_iter3_sum_2_reg_197 <= ap_phi_reg_pp0_iter2_sum_2_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_phi_reg_pp0_iter4_cnt_2_reg_206 <= ap_phi_reg_pp0_iter3_cnt_2_reg_206;
                ap_phi_reg_pp0_iter4_sum_2_reg_197 <= ap_phi_reg_pp0_iter3_sum_2_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_phi_reg_pp0_iter5_cnt_2_reg_206 <= ap_phi_reg_pp0_iter4_cnt_2_reg_206;
                ap_phi_reg_pp0_iter5_sum_2_reg_197 <= ap_phi_reg_pp0_iter4_sum_2_reg_197;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to23, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to23 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln72_fu_283_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_3) + unsigned(ap_const_lv31_1));
    add_ln75_fu_293_p2 <= std_logic_vector(unsigned(trunc_ln72_fu_289_p1) + unsigned(empty));
    add_ln76_1_fu_299_p2 <= std_logic_vector(unsigned(zext_ln67_1_cast_fu_243_p1) + unsigned(ap_const_lv9_1));
    add_ln76_fu_309_p2 <= std_logic_vector(unsigned(zext_ln76_fu_305_p1) + unsigned(zext_ln72_fu_273_p1));
    add_ln77_1_fu_347_p2 <= std_logic_vector(unsigned(add_ln77_fu_342_p2) + unsigned(sext_ln71_2_cast_reg_470));
    add_ln77_fu_342_p2 <= std_logic_vector(unsigned(zext_ln76_1_fu_336_p1) + unsigned(src));
    add_ln78_1_fu_370_p2 <= std_logic_vector(unsigned(add_ln78_fu_365_p2) + unsigned(sext_ln71_2_cast_reg_470));
    add_ln78_fu_365_p2 <= std_logic_vector(signed(sext_ln77_fu_339_p1) + signed(src));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state3_io, ap_block_state11_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state3_io, ap_block_state11_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state4_io, ap_block_state12_pp0_stage1_iter5)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage1_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_block_state4_io, ap_block_state12_pp0_stage1_iter5)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage1_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_state11_pp0_stage0_iter5_assign_proc : process(m_axi_gmem0_RVALID, ap_predicate_op112_read_state11)
    begin
                ap_block_state11_pp0_stage0_iter5 <= ((ap_predicate_op112_read_state11 = ap_const_boolean_1) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state12_pp0_stage1_iter5_assign_proc : process(m_axi_gmem0_RVALID, ap_predicate_op122_read_state12)
    begin
                ap_block_state12_pp0_stage1_iter5 <= ((ap_predicate_op122_read_state12 = ap_const_boolean_1) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem0_ARREADY, ap_predicate_op97_readreq_state3)
    begin
                ap_block_state3_io <= ((ap_predicate_op97_readreq_state3 = ap_const_boolean_1) and (m_axi_gmem0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem0_ARREADY, ap_predicate_op99_readreq_state4)
    begin
                ap_block_state4_io <= ((ap_predicate_op99_readreq_state4 = ap_const_boolean_1) and (m_axi_gmem0_ARREADY = ap_const_logic_0));
    end process;


    ap_condition_486_assign_proc : process(ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_486 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001));
    end process;


    ap_condition_796_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op97_readreq_state3, ap_block_pp0_stage0_11001)
    begin
                ap_condition_796 <= ((ap_predicate_op97_readreq_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_799_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_predicate_op99_readreq_state4, ap_block_pp0_stage1_11001)
    begin
                ap_condition_799 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op99_readreq_state4 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln72_reg_476, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln72_reg_476 = ap_const_lv1_0))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, icmp_ln72_reg_476_pp0_iter5_reg, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_0))) then 
            ap_condition_exit_pp0_iter5_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter22_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter22_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23)
    begin
        if (((ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) 
    and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to23_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23)
    begin
        if (((ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) 
    and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to23 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to23 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_phi_mux_cnt_3_phi_fu_228_p4_assign_proc : process(icmp_ln72_reg_476_pp0_iter5_reg, tmp_29_reg_506_pp0_iter5_reg, ap_phi_reg_pp0_iter6_cnt_2_reg_206, cnt_7_fu_418_p2, ap_phi_reg_pp0_iter6_cnt_3_reg_225)
    begin
        if ((icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1)) then
            if ((tmp_29_reg_506_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_cnt_3_phi_fu_228_p4 <= ap_phi_reg_pp0_iter6_cnt_2_reg_206;
            elsif ((tmp_29_reg_506_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_cnt_3_phi_fu_228_p4 <= cnt_7_fu_418_p2;
            else 
                ap_phi_mux_cnt_3_phi_fu_228_p4 <= ap_phi_reg_pp0_iter6_cnt_3_reg_225;
            end if;
        else 
            ap_phi_mux_cnt_3_phi_fu_228_p4 <= ap_phi_reg_pp0_iter6_cnt_3_reg_225;
        end if; 
    end process;


    ap_phi_mux_sum_3_phi_fu_218_p4_assign_proc : process(icmp_ln72_reg_476_pp0_iter5_reg, tmp_29_reg_506_pp0_iter5_reg, ap_phi_reg_pp0_iter6_sum_2_reg_197, sum_5_fu_411_p2, ap_phi_reg_pp0_iter6_sum_3_reg_215)
    begin
        if ((icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1)) then
            if ((tmp_29_reg_506_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_sum_3_phi_fu_218_p4 <= ap_phi_reg_pp0_iter6_sum_2_reg_197;
            elsif ((tmp_29_reg_506_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_sum_3_phi_fu_218_p4 <= sum_5_fu_411_p2;
            else 
                ap_phi_mux_sum_3_phi_fu_218_p4 <= ap_phi_reg_pp0_iter6_sum_3_reg_215;
            end if;
        else 
            ap_phi_mux_sum_3_phi_fu_218_p4 <= ap_phi_reg_pp0_iter6_sum_3_reg_215;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_cnt_2_reg_206 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sum_2_reg_197 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_cnt_3_reg_225 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_sum_3_reg_215 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op112_read_state11_assign_proc : process(icmp_ln72_reg_476_pp0_iter4_reg, icmp_ln77_reg_496_pp0_iter4_reg)
    begin
                ap_predicate_op112_read_state11 <= ((icmp_ln77_reg_496_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln72_reg_476_pp0_iter4_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op122_read_state12_assign_proc : process(icmp_ln72_reg_476_pp0_iter5_reg, tmp_29_reg_506_pp0_iter4_reg)
    begin
                ap_predicate_op122_read_state12 <= ((tmp_29_reg_506_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln72_reg_476_pp0_iter5_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op97_readreq_state3_assign_proc : process(icmp_ln72_reg_476, icmp_ln77_reg_496)
    begin
                ap_predicate_op97_readreq_state3 <= ((icmp_ln77_reg_496 = ap_const_lv1_1) and (icmp_ln72_reg_476 = ap_const_lv1_1));
    end process;


    ap_predicate_op99_readreq_state4_assign_proc : process(icmp_ln72_reg_476_pp0_iter1_reg, tmp_29_reg_506)
    begin
                ap_predicate_op99_readreq_state4 <= ((tmp_29_reg_506 = ap_const_lv1_0) and (icmp_ln72_reg_476_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_90, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_c_3 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_c_3 <= c_fu_90;
        end if; 
    end process;

    cnt_6_fu_402_p2 <= std_logic_vector(unsigned(cnt_fu_98) + unsigned(ap_const_lv32_1));
    cnt_7_fu_418_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter6_cnt_2_reg_206) + unsigned(ap_const_lv32_FFFFFFFF));

    gmem0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_axi_gmem0_ARREADY, icmp_ln72_reg_476, ap_predicate_op99_readreq_state4, ap_block_pp0_stage1, ap_block_pp0_stage0, icmp_ln77_reg_496)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln77_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln72_reg_476 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op99_readreq_state4 = ap_const_boolean_1)))) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, m_axi_gmem0_RVALID, ap_predicate_op122_read_state12, ap_block_pp0_stage1, ap_block_pp0_stage0, icmp_ln72_reg_476_pp0_iter4_reg, icmp_ln77_reg_496_pp0_iter4_reg)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln77_reg_496_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln72_reg_476_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op122_read_state12 = ap_const_boolean_1)))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_387_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            grp_fu_387_ce <= ap_const_logic_1;
        else 
            grp_fu_387_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln72_fu_277_p2 <= "1" when (signed(zext_ln72_fu_273_p1) < signed(width)) else "0";
    icmp_ln77_fu_325_p2 <= "1" when (signed(zext_ln76_2_fu_315_p1) < signed(sext_ln67_cast_fu_235_p1)) else "0";

    m_axi_gmem0_ARADDR_assign_proc : process(ap_enable_reg_pp0_iter1, gmem0_addr_reg_500, gmem0_addr_1_reg_510, ap_condition_796, ap_condition_799)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_799)) then 
                m_axi_gmem0_ARADDR <= gmem0_addr_1_reg_510;
            elsif ((ap_const_boolean_1 = ap_condition_796)) then 
                m_axi_gmem0_ARADDR <= gmem0_addr_reg_500;
            else 
                m_axi_gmem0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_gmem0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_1;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op99_readreq_state4, ap_predicate_op97_readreq_state3, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_predicate_op97_readreq_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op99_readreq_state4 = ap_const_boolean_1)))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_predicate_op122_read_state12, ap_predicate_op112_read_state11, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_predicate_op112_read_state11 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op122_read_state12 = ap_const_boolean_1)))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
        sext_ln67_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln67),33));

        sext_ln71_1_cast_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln71_1),32));

        sext_ln71_2_cast_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln71_2),64));

        sext_ln77_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln76_reg_490),64));

    sub_ln76_fu_319_p2 <= std_logic_vector(unsigned(zext_ln72_fu_273_p1) - unsigned(zext_ln67_cast_fu_239_p1));
    sum_4_fu_396_p2 <= std_logic_vector(unsigned(sum_fu_94) + unsigned(zext_ln77_fu_393_p1));
    sum_5_fu_411_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter6_sum_2_reg_197) - unsigned(zext_ln78_fu_408_p1));
    tmp_address1 <= zext_ln75_fu_439_p1(17 - 1 downto 0);

    tmp_ce1_assign_proc : process(ap_enable_reg_pp0_iter23, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter23 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            tmp_ce1 <= ap_const_logic_1;
        else 
            tmp_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_d1 <= sdiv_ln75_reg_548(8 - 1 downto 0);

    tmp_we1_assign_proc : process(ap_enable_reg_pp0_iter23, ap_CS_fsm_pp0_stage1, icmp_ln72_reg_476_pp0_iter23_reg, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter23 = ap_const_logic_1) and (icmp_ln72_reg_476_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            tmp_we1 <= ap_const_logic_1;
        else 
            tmp_we1 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln72_fu_289_p1 <= ap_sig_allocacmp_c_3(17 - 1 downto 0);
    zext_ln67_1_cast_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln67_1),9));
    zext_ln67_cast_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln67),32));
    zext_ln72_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_c_3),32));
    zext_ln75_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln75_reg_480_pp0_iter23_reg),64));
    zext_ln76_1_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_reg_485),64));
    zext_ln76_2_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_309_p2),33));
    zext_ln76_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_1_fu_299_p2),32));
    zext_ln77_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem0_addr_read_reg_516),32));
    zext_ln78_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(gmem0_addr_1_read_reg_543),32));
end behav;
